### ISSUE TITLE
Tailwindcss

### ISSUE THREAD

**Issue by K-Lorenz** [rickertmar/KinoticketFrontend#13]
Ich hab gesehen, dass ihr für jede Seite **ein eigenes Styleshee**t(bzw direkt in die js datei reinschreibt was es sein soll). Für einheitlichkeit der Website müsst ihr eine Library wie **[tailwindcss](https://v2.tailwindcss.com/docs)** benutzen. Wenn ihr damit nicht klar kommen solltet ist **[bootstrap](https://getbootstrap.com/docs/4.1/getting-started/introduction/)** auch eine Möglichkeit. Bitte dringend anfangen zu implementieren!

**Comment by LRaiden22** [comment]
ist gemacht brudibär
