### ISSUE TITLE
Navbar language + no Sign in option

### ISSUE THREAD

**Issue by zxTyphoon** [rickertmar/KinoticketFrontend#29]
Wir hatten uns auf english geeinigt.

Man kommt von keiner Seite zur Anmelde/Konto erstellen Seite.

**Comment by K-Lorenz** [comment]
Englisch werde ich fixen. Dafür, dass man die Anmelde Seite erreichen können, müssen wir zuerst die Authentifizierung machen. Wir wissen gerade ja noch nicht, ob der User angemeldet ist oder nicht. Fürs Testing kannst du eif die Seite aufrufen über die URL.

**Comment by zxTyphoon** [comment]
Ich hätte gesagt du machst einen Button in Navbar "Account" und wenn man darauf clickt wird abgefragt ob man schon authentifiziert ist, wenn nicht - LogInPage

**Comment by zxTyphoon** [comment]
Müssen aber sowieso jetzt zuerst schauen wie wir Token generieren + rumsenden mit request im Backend
