### ISSUE TITLE
Navbar for smallscreens not working

### ISSUE THREAD

**Issue by K-Lorenz** [rickertmar/KinoticketFrontend#30]
Navbar in Responsive design is Not working. Dropdown menu broken

**Comment by rickertmar** [comment]
> Navbar in Responsive design is Not working. Dropdown menu broken

Not working/shown and button action bug --> login popup opens on menu button; repro:

1. Responsive/mobile design
2. Click on login/account button and directly close popup
3. Click menu button -> menu not shown and login reopens

**Comment by rickertmar** [comment]
Please also think about changing the **menu buttons color to white**. I showed the page to someone and he didnt even notice the menu button (in darkmode).
