### ISSUE TITLE
Cinemock

### ISSUE THREAD

**Issue by K-Lorenz** [rickertmar/KinoticketFrontend#5]
Unser Kino heißt nicht CineMock bitte ändern ^^

**Comment by uiyoungkim** [comment]
Ich habe einfach das von Prototyp genommen aber DHBW Kino wäre schon schöner.
Wie hast du damals gemacht? 
Habe paar AI gesehen sind aber alle kostenpflichtig und wenn ich in Paint mache und anstelle CineMock DHBW KINO reinmache ist zu hässlich. Ideen?

**Comment by K-Lorenz** [comment]
Es gibt so Logo-Design websites. Ansonsten eif photoshop oder sowas benutzen. Im Notfall kann ich das auch machen.

**Comment by zxTyphoon** [comment]
![DHBWKino](https://github.com/rickertmar/KinoticketFrontend/assets/116372898/8137f15d-bac4-4939-8fcf-b426c43fb3b8)
