### ISSUE TITLE
Rework Seatspage

### ISSUE THREAD

**Issue by K-Lorenz** [rickertmar/KinoticketFrontend#64]
Rework the seatspage to dynamically load CinemaHall - Layout. Enabling the existence of pathways, stairs etc.

**Comment by rickertmar** [comment]
Mobile view with horizontal scrolling could also be reworked. **But dynamic loading with api request has prio.**

<img width="218" alt="image" src="https://github.com/rickertmar/KinoticketFrontend/assets/115364452/3a3266ac-ee3c-4a7a-85be-99b565fa4642">

Is it difficult to implement a zoom? at least for mobile?
<img width="238" alt="image" src="https://github.com/rickertmar/KinoticketFrontend/assets/115364452/405a85e7-7e68-45c4-b226-edb6fd1d1704">

**Comment by rickertmar** [comment]
Blocked (gray) seats can be selected and added to booking
