### ISSUE TITLE
Company Colors & Language

### ISSUE THREAD

**Issue by zxTyphoon** [rickertmar/KinoticketFrontend#9]
Haben wir uns jetzt auf Englisch oder Deutsch geeinigt? Und welche Farbpalette sollen wir benutzen?

**Comment by K-Lorenz** [comment]
Ich mein theoretisch können wir n language-switcher machen. Je nachdem wie viel Content das wird. Aber so Filme etc wird sowieso automatisch generiert. Wären also nur die grundlegenden dinge die man doppelt machen muss.
Wegen Farben: Würde nicht das Lila nehmen, finde das hässlich. Es gibt online so Farbpalettengeneratoren, vllt findet man da was?

**Comment by zxTyphoon** [comment]
Habe bisher Deutsch benutzt, Kim englisch...wäre halt gut zu wissen welches wir als Basis jetzt machen sollen (egal ob wir später Language Switcher einbauen) 
Für Farbpalette wäre es denke ich gut, es als Gruppe abzusprechen...wäre aber auch gut das beim Designen der Websites zu wissen und nicht bis Freitag warten zu müssen

**Comment by K-Lorenz** [comment]
also ich denke Englisch ist besser fürn Anfang.
Wegen Farbpalette vertrau ich dem Frontend-Team. Sucht eif was raus was in euren Augen gut aussieht. Ist halt eure Sache ich pass mich dann an.
